version: '2'

services:
  lambda-elasticsearch-snapshot:
    image: node:12.16
    entrypoint: sh
    working_dir: /usr/share/app
    volumes:
      - ~/.aws:/root/.aws
      - ~/.cache/yarn:/root/.cache/yarn
      - ./:/usr/share/app
